### ISSUE TITLE
Opensimplex

### ISSUE THREAD

**Issue by terekita** [dvschultz/stylegan2#3]
Hi, when running a stylegan2 interpolating colab notebook (think it perhaps used to be in your repo?, don't see it there now), run_generator.py from your repo was choking with "no module named 'opensimplex' " . I just commented out that line in the run_generator.py code and then the colab file worked fine...

Incidentally this is the line from the colab file:
!python run_generator.py generate-images --network='/content/gdrive/My Drive/Pickles/network-snapshot-000117.pkl' --seeds=1-1000 --truncation-psi=1.0

**Comment by dvschultz** [comment]
you can fix this by adding `pip install opensimplex` in your colab notebook right after you clone the repo. Some new functions added to the generator require this library now.

**Comment by terekita** [comment]
perfect, thanks!
